---
# --------------------------------

- name: "Include common pre-tasks"
  ansible.builtin.include_tasks: common-pre.yml
  tags: [ct-brave]

- name: "Include {{ ct_family }} tasks"
  ansible.builtin.include_tasks: setup-{{ ct_family }}.yml
  when:
  - ct_family == "debian" or ct_family == "redhat"
  tags: [ct-brave]

- name: "Include comon post-tasks"
  ansible.builtin.include_tasks: common-post.yml
  tags: [ct-brave]

# --------------------------------
...
