---
# --------------------------------

- name: "Install some packages so we can install the repo key"
  ansible.builtin.apt:
    name: "{{ brave_dependencies }}"
    state: present
  become: true
  tags: [ct-brave]

- name: "Add Brave repo key"
  ansible.builtin.apt_key:
    state: present
    url: "{{ brave_repo_key }}"
    validate_certs: true
  become: true
  tags: [ct-brave]

- name: "Add Brave repository to APT"
  ansible.builtin.apt_repository:
    filename: "brave-browser-release.list"
    repo: "{{ brave_repo_path }}"
    state: present
    update_cache: true
  register: reg_brave_repo
  become: true
  tags: [ct-brave]

- name: "Update APT cache and install Brave"
  ansible.builtin.apt:
    name: "{{ brave_packages }}"
    update_cache: "{{ reg_brave_repo is changed }}"
    state: present
  become: true
  tags: [ct-brave]

# --------------------------------
...
